# Generated by Django 4.0.6 on 2022-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
