# Generated by Django 4.0.6 on 2022-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_server_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='life',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Decomissioned', 'Decomissioned'), ('In Maintenance', 'In Maintenance'), ('Repair', 'Repair'), ('Provisioning', 'Provisioning')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_family',
            field=models.CharField(blank=True, choices=[('Unix', 'Unix'), ('Win', 'Windows')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Stopped', 'Stopped'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
    ]
