# Generated by Django 4.0.6 on 2022-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_servermetrics_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetrics',
            name='CpuUsage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CpuUsage',
        ),
    ]
