# Generated by Django 4.0.6 on 2022-08-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_delete_cpuusagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('host_ipaddress', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('port', models.CharField(blank=True, max_length=20, null=True)),
                ('database_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.databasetype')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.server')),
            ],
        ),
    ]
