# Generated by Django 4.0.6 on 2022-08-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_delete_database_delete_databasetype'),
        ('database', '0005_alter_database_database_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='host_ipaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_ip', to='inventory.server', to_field='ip_address'),
        ),
    ]
