# Generated by Django 4.0.6 on 2022-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_database_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='host_ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True),
        ),
    ]
