# Generated by Django 4.0.6 on 2022-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopped', 'Stopped'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('life', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Decomissioned', 'Decomissioned'), ('In Maintenance', 'In Maintenance'), ('Repair', 'Repair'), ('Provisioning', 'Provisioning')], max_length=20)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', unique=True)),
                ('server_role', models.CharField(blank=True, choices=[('Prod', 'Prod'), ('Test', 'Test'), ('Dev', 'Dev'), ('UAT', 'UAT')], max_length=20, null=True)),
                ('host_type', models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], max_length=20, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('os_family', models.CharField(choices=[('Unix', 'Unix'), ('Win', 'Windows')], max_length=20)),
                ('applications_hosted', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('support_group', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('site', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['server_name', 'hostname', 'ip_address'], name='Idx_ServerHostname'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['status', 'life'], name='Idx_ServerStatus'),
        ),
    ]
