# Generated by Django 4.0.6 on 2022-08-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_server_ip_address_alter_server_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cores', models.SmallIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.server')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
