# Generated by Django 4.0.6 on 2022-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_cpuusage_cpuusage_servermetrics_load_average1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetrics',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10),
        ),
    ]
