# Generated by Django 4.0.6 on 2022-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_cpuusage_servermetrics_cpu_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetrics',
            name='free_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='total_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MemoryUsage',
        ),
    ]
