# Generated by Django 4.0.6 on 2022-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_servermetrics_free_memory_servermetrics_total_memory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskvolumes',
            old_name='capacity',
            new_name='total_size',
        ),
        migrations.AddField(
            model_name='diskvolumes',
            name='used_space',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='swap_free',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='swap_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='swap_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermetrics',
            name='used_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
