# Generated by Django 4.0.6 on 2022-08-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_cpuusagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('total_memory', models.IntegerField(blank=True, null=True)),
                ('free_memory', models.IntegerField(blank=True, null=True)),
                ('used_memory', models.IntegerField(blank=True, null=True)),
                ('free_memory_pc', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('used_memory_pc', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('swap_total', models.IntegerField(blank=True, null=True)),
                ('swap_free', models.IntegerField(blank=True, null=True)),
                ('swap_used', models.IntegerField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.server')),
            ],
        ),
    ]
