# Generated by Django 4.0.6 on 2022-08-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_cpumemoryusagehistory_delete_memoryusagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CpuUsageHistory',
        ),
    ]
