# Generated by Django 4.0.6 on 2022-08-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_delete_database_delete_databasetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-id']},
        ),
    ]
