# Generated by Django 4.0.6 on 2022-08-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_database_host_ipaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='host_ipaddress2',
        ),
    ]
