# Generated by Django 4.0.6 on 2022-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_database_host_ipaddress2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
