# Generated by Django 4.0.6 on 2022-08-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_delete_database_delete_databasetype'),
        ('database', '0006_database_host_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='hostname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.server', to_field='server_name'),
        ),
    ]
