# Generated by Django 4.0.6 on 2022-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_database_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.CharField(blank=True, choices=[('UP', 'UP'), ('Down', 'Down')], max_length=20, null=True),
        ),
    ]
