# Generated by Django 4.0.6 on 2022-08-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_delete_database_delete_databasetype'),
        ('database', '0009_alter_database_host_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='database_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.databasetype', to_field='database_type'),
        ),
        migrations.AlterField(
            model_name='database',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.server', to_field='server_name'),
        ),
        migrations.AlterField(
            model_name='database',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
