# Generated by Django 4.0.6 on 2022-08-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_database_database_type_alter_database_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='host_ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
